@extends('layouts.app')
@section('title', ($settings['agency_name'] ?? 'Mountain Trails').' | Himachal, Uttarakhand & Manali Packages')
@section('content')
<section id="home" class="relative flex min-h-[680px] items-end overflow-hidden bg-forest pt-24">
  <img src="/images/hero.jpg" alt="Mountain landscape" class="absolute inset-0 h-full w-full object-cover opacity-75">
  <div class="absolute inset-0 bg-gradient-to-t from-ink via-ink/35 to-transparent"></div>
  <div class="container-shell relative z-10 pb-20 pt-28">
    <div class="max-w-3xl text-white">
      <span class="inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.2em]">Mountain escapes · India</span>
      <h1 class="mt-6 text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">{{ $settings['hero_title'] ?? 'Explore The Mountains. Create Memories.' }}</h1>
      <p class="mt-6 max-w-2xl text-lg leading-8 text-white/80">{{ $settings['hero_description'] ?? '' }}</p>
      <div class="mt-8 flex flex-wrap gap-3"><a href="#packages" class="btn bg-sand text-ink">Explore Packages</a><a href="#contact" class="btn border border-white/30 bg-white/10 text-white">Contact Us</a></div>
    </div>
  </div>
</section>
<section id="packages" class="py-20 sm:py-24"><div class="container-shell"><div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="text-sm font-bold uppercase tracking-[0.2em] text-forest">Choose your escape</p><h2 class="mt-2 text-4xl sm:text-5xl">Explore Our Packages</h2></div><p class="max-w-md text-slate-500">Three simple ways to start planning a mountain trip, with direct enquiry support when you are ready.</p></div><div class="mt-10 grid gap-6 lg:grid-cols-3">
@foreach($packages as $package)
<article class="card group overflow-hidden"><div class="relative h-64 overflow-hidden"><img src="{{ $package['image'] }}" alt="{{ $package['name'] }} destination" class="h-full w-full object-cover transition duration-500 group-hover:scale-105"><div class="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-xs font-bold text-forest">{{ $package['duration'] }}</div></div><div class="p-6"><div class="flex items-start justify-between gap-4"><h3 class="text-2xl">{{ $package['name'] }}</h3><div class="whitespace-nowrap text-right"><div class="text-xs text-slate-400">Starting</div><div class="font-bold text-forest">{{ $package['price'] }}</div></div></div><p class="mt-3 text-sm leading-6 text-slate-500">{{ $package['short_description'] }}</p><div class="mt-5 flex flex-wrap gap-2">@foreach($package['highlights'] as $highlight)<span class="rounded-full bg-mist px-3 py-1 text-xs font-semibold text-forest">✓ {{ $highlight }}</span>@endforeach</div><a href="{{ route('contact', ['package' => $package['slug']]) }}" class="btn-primary mt-6 w-full">Enquire Now</a></div></article>
@endforeach
</div></div></section>
<section class="bg-mist py-20"><div class="container-shell"><div class="max-w-xl"><p class="text-sm font-bold uppercase tracking-[0.2em] text-forest">Why travel with us</p><h2 class="mt-2 text-4xl sm:text-5xl">Planning should feel easy.</h2></div><div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-3xl bg-white p-6"><div class="text-2xl">◌</div><h3 class="mt-5 text-xl">Experienced Travel Support</h3><p class="mt-2 text-sm leading-6 text-slate-500">Get assistance throughout your travel planning.</p></div><div class="rounded-3xl bg-white p-6"><div class="text-2xl">◇</div><h3 class="mt-5 text-xl">Affordable Packages</h3><p class="mt-2 text-sm leading-6 text-slate-500">Travel packages designed to provide great value.</p></div><div class="rounded-3xl bg-white p-6"><div class="text-2xl">⌁</div><h3 class="mt-5 text-xl">Customized Travel Planning</h3><p class="mt-2 text-sm leading-6 text-slate-500">Packages can be adjusted according to your requirements.</p></div><div class="rounded-3xl bg-white p-6"><div class="text-2xl">↗</div><h3 class="mt-5 text-xl">Quick Customer Support</h3><p class="mt-2 text-sm leading-6 text-slate-500">Get quick assistance through phone and WhatsApp.</p></div></div></div></section>
<section id="contact" class="py-20 sm:py-24"><div class="container-shell"><div class="overflow-hidden rounded-[2rem] bg-forest px-7 py-12 text-white sm:px-12"><div class="max-w-2xl"><p class="text-sm font-bold uppercase tracking-[0.2em] text-sand">Ready to plan?</p><h2 class="mt-3 text-4xl sm:text-5xl">Ready to Plan Your Trip?</h2><p class="mt-4 text-white/70">Talk to our travel team and start planning your next mountain getaway.</p><div class="mt-7 flex flex-wrap gap-3"><a class="btn bg-sand text-ink" href="tel:{{ $settings['phone'] ?? '' }}">Call Now</a><a class="btn border border-white/20 bg-white/10 text-white" href="https://wa.me/{{ $settings['whatsapp'] ?? '' }}">WhatsApp Us</a></div></div></div></div></section>
@endsection
